import type { IAuthenticateGeneric, ICredentialType, INodeProperties } from 'n8n-workflow';

export class ArvanAiApi implements ICredentialType {
	name = 'arvanAiApi';

	displayName = 'ArvanCloud AIaaS API';

	documentationUrl = 'https://docs.arvancloud.ir/fa/aiaas/api-usage/';

	properties: INodeProperties[] = [
		{
			displayName: 'Endpoint URL',
			name: 'endpointUrl',
			type: 'string',
			default: '',
			placeholder: 'https://arvancloudai.ir/gateway/models/.../.../v1',
			description:
				'The unique AIaaS endpoint URL generated by ArvanCloud. Use the base URL ending in /v1, not /chat/completions.',
			required: true,
		},
		{
			displayName: 'API Key',
			name: 'apiKey',
			type: 'string',
			typeOptions: { password: true },
			default: '',
			placeholder: 'apikey ...',
			description:
				'Paste the complete ArvanCloud access key exactly as shown in the AIaaS examples, including the "apikey " prefix when present.',
			required: true,
		},
	];

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {
			headers: {
				Authorization: '=Bearer {{$credentials?.apiKey}}',
				'Content-Type': 'application/json',
			},
		},
	};
}
